import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const avenirBlack = localFont({
  src: "./fonts/AvenirLTStd-Black.woff",
  variable: "--font-avenir-bold",
  weight: "100 900",
});
const avenirLight = localFont({
  src: "./fonts/AvenirLTStd-Light.woff",
  variable: "--font-avenir-light",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${avenirBlack.variable} ${avenirLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
